// Subset of HBase protobuf definitions needed for reading snapshot manifests.
// Derived from hbase-protocol/src/main/protobuf/Snapshot.proto, HBase.proto,
// and FS.proto.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.33.4
// source: snapshot/proto/snapshot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reference_Range int32

const (
	Reference_TOP    Reference_Range = 0
	Reference_BOTTOM Reference_Range = 1
)

// Enum value maps for Reference_Range.
var (
	Reference_Range_name = map[int32]string{
		0: "TOP",
		1: "BOTTOM",
	}
	Reference_Range_value = map[string]int32{
		"TOP":    0,
		"BOTTOM": 1,
	}
)

func (x Reference_Range) Enum() *Reference_Range {
	p := new(Reference_Range)
	*p = x
	return p
}

func (x Reference_Range) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reference_Range) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_proto_snapshot_proto_enumTypes[0].Descriptor()
}

func (Reference_Range) Type() protoreflect.EnumType {
	return &file_snapshot_proto_snapshot_proto_enumTypes[0]
}

func (x Reference_Range) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *Reference_Range) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = Reference_Range(num)
	return nil
}

// Deprecated: Use Reference_Range.Descriptor instead.
func (Reference_Range) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_proto_snapshot_proto_rawDescGZIP(), []int{6, 0}
}

type SnapshotDescription_Type int32

const (
	SnapshotDescription_DISABLED  SnapshotDescription_Type = 0
	SnapshotDescription_FLUSH     SnapshotDescription_Type = 1
	SnapshotDescription_SKIPFLUSH SnapshotDescription_Type = 2
)

// Enum value maps for SnapshotDescription_Type.
var (
	SnapshotDescription_Type_name = map[int32]string{
		0: "DISABLED",
		1: "FLUSH",
		2: "SKIPFLUSH",
	}
	SnapshotDescription_Type_value = map[string]int32{
		"DISABLED":  0,
		"FLUSH":     1,
		"SKIPFLUSH": 2,
	}
)

func (x SnapshotDescription_Type) Enum() *SnapshotDescription_Type {
	p := new(SnapshotDescription_Type)
	*p = x
	return p
}

func (x SnapshotDescription_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotDescription_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_proto_snapshot_proto_enumTypes[1].Descriptor()
}

func (SnapshotDescription_Type) Type() protoreflect.EnumType {
	return &file_snapshot_proto_snapshot_proto_enumTypes[1]
}

func (x SnapshotDescription_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SnapshotDescription_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SnapshotDescription_Type(num)
	return nil
}

// Deprecated: Use SnapshotDescription_Type.Descriptor instead.
func (SnapshotDescription_Type) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_proto_snapshot_proto_rawDescGZIP(), []int{7, 0}
}

type TableName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace []byte `protobuf:"bytes,1,req,name=namespace" json:"namespace,omitempty"`
	Qualifier []byte `protobuf:"bytes,2,req,name=qualifier" json:"qualifier,omitempty"`
}

func (x *TableName) Reset() {
	*x = TableName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_proto_snapshot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableName) ProtoMessage() {}

func (x *TableName) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_snapshot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableName.ProtoReflect.Descriptor instead.
func (*TableName) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *TableName) GetNamespace() []byte {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *TableName) GetQualifier() []byte {
	if x != nil {
		return x.Qualifier
	}
	return nil
}

type ColumnFamilySchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          []byte            `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Attributes    []*BytesBytesPair `protobuf:"bytes,2,rep,name=attributes" json:"attributes,omitempty"`
	Configuration []*NameStringPair `protobuf:"bytes,3,rep,name=configuration" json:"configuration,omitempty"`
}

func (x *ColumnFamilySchema) Reset() {
	*x = ColumnFamilySchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_proto_snapshot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnFamilySchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnFamilySchema) ProtoMessage() {}

func (x *ColumnFamilySchema) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_snapshot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnFamilySchema.ProtoReflect.Descriptor instead.
func (*ColumnFamilySchema) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *ColumnFamilySchema) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *ColumnFamilySchema) GetAttributes() []*BytesBytesPair {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ColumnFamilySchema) GetConfiguration() []*NameStringPair {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type TableSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName      *TableName            `protobuf:"bytes,1,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	Attributes     []*BytesBytesPair     `protobuf:"bytes,2,rep,name=attributes" json:"attributes,omitempty"`
	ColumnFamilies []*ColumnFamilySchema `protobuf:"bytes,3,rep,name=column_families,json=columnFamilies" json:"column_families,omitempty"`
	Configuration  []*NameStringPair     `protobuf:"bytes,4,rep,name=configuration" json:"configuration,omitempty"`
}

func (x *TableSchema) Reset() {
	*x = TableSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_proto_snapshot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TableSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSchema) ProtoMessage() {}

func (x *TableSchema) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_snapshot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSchema.ProtoReflect.Descriptor instead.
func (*TableSchema) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_snapshot_proto_rawDescGZIP(), []int{2}
}

func (x *TableSchema) GetTableName() *TableName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *TableSchema) GetAttributes() []*BytesBytesPair {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *TableSchema) GetColumnFamilies() []*ColumnFamilySchema {
	if x != nil {
		return x.ColumnFamilies
	}
	return nil
}

func (x *TableSchema) GetConfiguration() []*NameStringPair {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type BytesBytesPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	First  []byte `protobuf:"bytes,1,req,name=first" json:"first,omitempty"`
	Second []byte `protobuf:"bytes,2,req,name=second" json:"second,omitempty"`
}

func (x *BytesBytesPair) Reset() {
	*x = BytesBytesPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_proto_snapshot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesBytesPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesBytesPair) ProtoMessage() {}

func (x *BytesBytesPair) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_snapshot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesBytesPair.ProtoReflect.Descriptor instead.
func (*BytesBytesPair) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_snapshot_proto_rawDescGZIP(), []int{3}
}

func (x *BytesBytesPair) GetFirst() []byte {
	if x != nil {
		return x.First
	}
	return nil
}

func (x *BytesBytesPair) GetSecond() []byte {
	if x != nil {
		return x.Second
	}
	return nil
}

type NameStringPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
}

func (x *NameStringPair) Reset() {
	*x = NameStringPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_proto_snapshot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NameStringPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameStringPair) ProtoMessage() {}

func (x *NameStringPair) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_snapshot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameStringPair.ProtoReflect.Descriptor instead.
func (*NameStringPair) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_snapshot_proto_rawDescGZIP(), []int{4}
}

func (x *NameStringPair) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *NameStringPair) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type RegionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegionId  *uint64    `protobuf:"varint,1,req,name=region_id,json=regionId" json:"region_id,omitempty"`
	TableName *TableName `protobuf:"bytes,2,req,name=table_name,json=tableName" json:"table_name,omitempty"`
	StartKey  []byte     `protobuf:"bytes,3,opt,name=start_key,json=startKey" json:"start_key,omitempty"`
	EndKey    []byte     `protobuf:"bytes,4,opt,name=end_key,json=endKey" json:"end_key,omitempty"`
	Offline   *bool      `protobuf:"varint,5,opt,name=offline" json:"offline,omitempty"`
	Split     *bool      `protobuf:"varint,6,opt,name=split" json:"split,omitempty"`
	ReplicaId *int32     `protobuf:"varint,7,opt,name=replica_id,json=replicaId,def=0" json:"replica_id,omitempty"`
}

// Default values for RegionInfo fields.
const (
	Default_RegionInfo_ReplicaId = int32(0)
)

func (x *RegionInfo) Reset() {
	*x = RegionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_proto_snapshot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionInfo) ProtoMessage() {}

func (x *RegionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_snapshot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionInfo.ProtoReflect.Descriptor instead.
func (*RegionInfo) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_snapshot_proto_rawDescGZIP(), []int{5}
}

func (x *RegionInfo) GetRegionId() uint64 {
	if x != nil && x.RegionId != nil {
		return *x.RegionId
	}
	return 0
}

func (x *RegionInfo) GetTableName() *TableName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *RegionInfo) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *RegionInfo) GetEndKey() []byte {
	if x != nil {
		return x.EndKey
	}
	return nil
}

func (x *RegionInfo) GetOffline() bool {
	if x != nil && x.Offline != nil {
		return *x.Offline
	}
	return false
}

func (x *RegionInfo) GetSplit() bool {
	if x != nil && x.Split != nil {
		return *x.Split
	}
	return false
}

func (x *RegionInfo) GetReplicaId() int32 {
	if x != nil && x.ReplicaId != nil {
		return *x.ReplicaId
	}
	return Default_RegionInfo_ReplicaId
}

type Reference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Splitkey []byte           `protobuf:"bytes,1,req,name=splitkey" json:"splitkey,omitempty"`
	Range    *Reference_Range `protobuf:"varint,2,req,name=range,enum=hbase.pb.Reference_Range" json:"range,omitempty"`
}

func (x *Reference) Reset() {
	*x = Reference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_proto_snapshot_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_snapshot_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_snapshot_proto_rawDescGZIP(), []int{6}
}

func (x *Reference) GetSplitkey() []byte {
	if x != nil {
		return x.Splitkey
	}
	return nil
}

func (x *Reference) GetRange() Reference_Range {
	if x != nil && x.Range != nil {
		return *x.Range
	}
	return Reference_TOP
}

type SnapshotDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         *string                   `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Table        *string                   `protobuf:"bytes,2,opt,name=table" json:"table,omitempty"`
	CreationTime *int64                    `protobuf:"varint,3,opt,name=creation_time,json=creationTime,def=0" json:"creation_time,omitempty"`
	Type         *SnapshotDescription_Type `protobuf:"varint,4,opt,name=type,enum=hbase.pb.SnapshotDescription_Type,def=1" json:"type,omitempty"`
	Version      *int32                    `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	Owner        *string                   `protobuf:"bytes,6,opt,name=owner" json:"owner,omitempty"`
	Ttl          *int64                    `protobuf:"varint,8,opt,name=ttl,def=0" json:"ttl,omitempty"`
	MaxFileSize  *int64                    `protobuf:"varint,9,opt,name=max_file_size,json=maxFileSize,def=0" json:"max_file_size,omitempty"`
}

// Default values for SnapshotDescription fields.
const (
	Default_SnapshotDescription_CreationTime = int64(0)
	Default_SnapshotDescription_Type         = SnapshotDescription_FLUSH
	Default_SnapshotDescription_Ttl          = int64(0)
	Default_SnapshotDescription_MaxFileSize  = int64(0)
)

func (x *SnapshotDescription) Reset() {
	*x = SnapshotDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_proto_snapshot_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDescription) ProtoMessage() {}

func (x *SnapshotDescription) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_snapshot_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDescription.ProtoReflect.Descriptor instead.
func (*SnapshotDescription) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_snapshot_proto_rawDescGZIP(), []int{7}
}

func (x *SnapshotDescription) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SnapshotDescription) GetTable() string {
	if x != nil && x.Table != nil {
		return *x.Table
	}
	return ""
}

func (x *SnapshotDescription) GetCreationTime() int64 {
	if x != nil && x.CreationTime != nil {
		return *x.CreationTime
	}
	return Default_SnapshotDescription_CreationTime
}

func (x *SnapshotDescription) GetType() SnapshotDescription_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Default_SnapshotDescription_Type
}

func (x *SnapshotDescription) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *SnapshotDescription) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *SnapshotDescription) GetTtl() int64 {
	if x != nil && x.Ttl != nil {
		return *x.Ttl
	}
	return Default_SnapshotDescription_Ttl
}

func (x *SnapshotDescription) GetMaxFileSize() int64 {
	if x != nil && x.MaxFileSize != nil {
		return *x.MaxFileSize
	}
	return Default_SnapshotDescription_MaxFileSize
}

type SnapshotRegionManifest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version     *int32                                `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	RegionInfo  *RegionInfo                           `protobuf:"bytes,2,req,name=region_info,json=regionInfo" json:"region_info,omitempty"`
	FamilyFiles []*SnapshotRegionManifest_FamilyFiles `protobuf:"bytes,3,rep,name=family_files,json=familyFiles" json:"family_files,omitempty"`
}

func (x *SnapshotRegionManifest) Reset() {
	*x = SnapshotRegionManifest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_proto_snapshot_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRegionManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRegionManifest) ProtoMessage() {}

func (x *SnapshotRegionManifest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_snapshot_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRegionManifest.ProtoReflect.Descriptor instead.
func (*SnapshotRegionManifest) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_snapshot_proto_rawDescGZIP(), []int{8}
}

func (x *SnapshotRegionManifest) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *SnapshotRegionManifest) GetRegionInfo() *RegionInfo {
	if x != nil {
		return x.RegionInfo
	}
	return nil
}

func (x *SnapshotRegionManifest) GetFamilyFiles() []*SnapshotRegionManifest_FamilyFiles {
	if x != nil {
		return x.FamilyFiles
	}
	return nil
}

type SnapshotDataManifest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableSchema     *TableSchema              `protobuf:"bytes,1,req,name=table_schema,json=tableSchema" json:"table_schema,omitempty"`
	RegionManifests []*SnapshotRegionManifest `protobuf:"bytes,2,rep,name=region_manifests,json=regionManifests" json:"region_manifests,omitempty"`
}

func (x *SnapshotDataManifest) Reset() {
	*x = SnapshotDataManifest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_proto_snapshot_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotDataManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDataManifest) ProtoMessage() {}

func (x *SnapshotDataManifest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_snapshot_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDataManifest.ProtoReflect.Descriptor instead.
func (*SnapshotDataManifest) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_snapshot_proto_rawDescGZIP(), []int{9}
}

func (x *SnapshotDataManifest) GetTableSchema() *TableSchema {
	if x != nil {
		return x.TableSchema
	}
	return nil
}

func (x *SnapshotDataManifest) GetRegionManifests() []*SnapshotRegionManifest {
	if x != nil {
		return x.RegionManifests
	}
	return nil
}

type SnapshotRegionManifest_StoreFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      *string    `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Reference *Reference `protobuf:"bytes,2,opt,name=reference" json:"reference,omitempty"`
	FileSize  *uint64    `protobuf:"varint,3,opt,name=file_size,json=fileSize" json:"file_size,omitempty"`
}

func (x *SnapshotRegionManifest_StoreFile) Reset() {
	*x = SnapshotRegionManifest_StoreFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_proto_snapshot_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRegionManifest_StoreFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRegionManifest_StoreFile) ProtoMessage() {}

func (x *SnapshotRegionManifest_StoreFile) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_snapshot_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRegionManifest_StoreFile.ProtoReflect.Descriptor instead.
func (*SnapshotRegionManifest_StoreFile) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_snapshot_proto_rawDescGZIP(), []int{8, 0}
}

func (x *SnapshotRegionManifest_StoreFile) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SnapshotRegionManifest_StoreFile) GetReference() *Reference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *SnapshotRegionManifest_StoreFile) GetFileSize() uint64 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

type SnapshotRegionManifest_FamilyFiles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FamilyName []byte                              `protobuf:"bytes,1,req,name=family_name,json=familyName" json:"family_name,omitempty"`
	StoreFiles []*SnapshotRegionManifest_StoreFile `protobuf:"bytes,2,rep,name=store_files,json=storeFiles" json:"store_files,omitempty"`
}

func (x *SnapshotRegionManifest_FamilyFiles) Reset() {
	*x = SnapshotRegionManifest_FamilyFiles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_snapshot_proto_snapshot_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotRegionManifest_FamilyFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRegionManifest_FamilyFiles) ProtoMessage() {}

func (x *SnapshotRegionManifest_FamilyFiles) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_proto_snapshot_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRegionManifest_FamilyFiles.ProtoReflect.Descriptor instead.
func (*SnapshotRegionManifest_FamilyFiles) Descriptor() ([]byte, []int) {
	return file_snapshot_proto_snapshot_proto_rawDescGZIP(), []int{8, 1}
}

func (x *SnapshotRegionManifest_FamilyFiles) GetFamilyName() []byte {
	if x != nil {
		return x.FamilyName
	}
	return nil
}

func (x *SnapshotRegionManifest_FamilyFiles) GetStoreFiles() []*SnapshotRegionManifest_StoreFile {
	if x != nil {
		return x.StoreFiles
	}
	return nil
}

var File_snapshot_proto_snapshot_proto protoreflect.FileDescriptor

var file_snapshot_proto_snapshot_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x22, 0x47, 0x0a, 0x09, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x09, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x22, 0xa2, 0x01, 0x0a, 0x12, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x46, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a,
	0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x42, 0x79, 0x74, 0x65, 0x73, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0a, 0x61, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x82, 0x02, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x32, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x45, 0x0a, 0x0f, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x5f,
	0x66, 0x61, 0x6d, 0x69, 0x6c, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x0e, 0x63, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x69, 0x65, 0x73, 0x12, 0x3e, 0x0a, 0x0d,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x4e,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x69, 0x72, 0x52, 0x0d, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3e, 0x0a, 0x0e,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x42, 0x79, 0x74, 0x65, 0x73, 0x50, 0x61, 0x69, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x05, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x3a, 0x0a, 0x0e,
	0x4e, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x69, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xe5, 0x01, 0x0a, 0x0a, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x0a, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x09, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x65, 0x6e, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x6c, 0x69,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x12, 0x20,
	0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x3a, 0x01, 0x30, 0x52, 0x09, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x49, 0x64,
	0x22, 0x76, 0x0a, 0x09, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52,
	0x08, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x6b, 0x65, 0x79, 0x12, 0x2f, 0x0a, 0x05, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x1c, 0x0a, 0x05, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x4f, 0x50, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x42, 0x4f, 0x54, 0x54, 0x4f, 0x4d, 0x10, 0x01, 0x22, 0xc2, 0x02, 0x0a, 0x13, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x0d, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x3a, 0x01, 0x30, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x22, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x3a, 0x05, 0x46, 0x4c, 0x55, 0x53, 0x48, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x12, 0x13, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x3a, 0x01,
	0x30, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x25, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x3a, 0x01, 0x30,
	0x52, 0x0b, 0x6d, 0x61, 0x78, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x2e, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c, 0x55, 0x53, 0x48, 0x10, 0x01, 0x12, 0x0d,
	0x0a, 0x09, 0x53, 0x4b, 0x49, 0x50, 0x46, 0x4c, 0x55, 0x53, 0x48, 0x10, 0x02, 0x22, 0xa8, 0x03,
	0x0a, 0x16, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x4f, 0x0a, 0x0c, 0x66, 0x61, 0x6d,
	0x69, 0x6c, 0x79, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2c, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73,
	0x68, 0x6f, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73,
	0x74, 0x2e, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x52, 0x0b, 0x66,
	0x61, 0x6d, 0x69, 0x6c, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x1a, 0x6f, 0x0a, 0x09, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x09, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x1a, 0x7b, 0x0a, 0x0b, 0x46,
	0x61, 0x6d, 0x69, 0x6c, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x61,
	0x6d, 0x69, 0x6c, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0c, 0x52,
	0x0a, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x4b, 0x0a, 0x0b, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2a, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x6e, 0x61, 0x70,
	0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65,
	0x73, 0x74, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x0a, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x9d, 0x01, 0x0a, 0x14, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73,
	0x74, 0x12, 0x38, 0x0a, 0x0c, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x70, 0x62, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x0b,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x4b, 0x0a, 0x10, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4d,
	0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x52, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x4d,
	0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x73, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x74, 0x68, 0x69, 0x2f, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x62, 0x65, 0x64, 0x2f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f,
}

var (
	file_snapshot_proto_snapshot_proto_rawDescOnce sync.Once
	file_snapshot_proto_snapshot_proto_rawDescData = file_snapshot_proto_snapshot_proto_rawDesc
)

func file_snapshot_proto_snapshot_proto_rawDescGZIP() []byte {
	file_snapshot_proto_snapshot_proto_rawDescOnce.Do(func() {
		file_snapshot_proto_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(file_snapshot_proto_snapshot_proto_rawDescData)
	})
	return file_snapshot_proto_snapshot_proto_rawDescData
}

var file_snapshot_proto_snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_snapshot_proto_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_snapshot_proto_snapshot_proto_goTypes = []interface{}{
	(Reference_Range)(0),                       // 0: hbase.pb.Reference.Range
	(SnapshotDescription_Type)(0),              // 1: hbase.pb.SnapshotDescription.Type
	(*TableName)(nil),                          // 2: hbase.pb.TableName
	(*ColumnFamilySchema)(nil),                 // 3: hbase.pb.ColumnFamilySchema
	(*TableSchema)(nil),                        // 4: hbase.pb.TableSchema
	(*BytesBytesPair)(nil),                     // 5: hbase.pb.BytesBytesPair
	(*NameStringPair)(nil),                     // 6: hbase.pb.NameStringPair
	(*RegionInfo)(nil),                         // 7: hbase.pb.RegionInfo
	(*Reference)(nil),                          // 8: hbase.pb.Reference
	(*SnapshotDescription)(nil),                // 9: hbase.pb.SnapshotDescription
	(*SnapshotRegionManifest)(nil),             // 10: hbase.pb.SnapshotRegionManifest
	(*SnapshotDataManifest)(nil),               // 11: hbase.pb.SnapshotDataManifest
	(*SnapshotRegionManifest_StoreFile)(nil),   // 12: hbase.pb.SnapshotRegionManifest.StoreFile
	(*SnapshotRegionManifest_FamilyFiles)(nil), // 13: hbase.pb.SnapshotRegionManifest.FamilyFiles
}
var file_snapshot_proto_snapshot_proto_depIdxs = []int32{
	5,  // 0: hbase.pb.ColumnFamilySchema.attributes:type_name -> hbase.pb.BytesBytesPair
	6,  // 1: hbase.pb.ColumnFamilySchema.configuration:type_name -> hbase.pb.NameStringPair
	2,  // 2: hbase.pb.TableSchema.table_name:type_name -> hbase.pb.TableName
	5,  // 3: hbase.pb.TableSchema.attributes:type_name -> hbase.pb.BytesBytesPair
	3,  // 4: hbase.pb.TableSchema.column_families:type_name -> hbase.pb.ColumnFamilySchema
	6,  // 5: hbase.pb.TableSchema.configuration:type_name -> hbase.pb.NameStringPair
	2,  // 6: hbase.pb.RegionInfo.table_name:type_name -> hbase.pb.TableName
	0,  // 7: hbase.pb.Reference.range:type_name -> hbase.pb.Reference.Range
	1,  // 8: hbase.pb.SnapshotDescription.type:type_name -> hbase.pb.SnapshotDescription.Type
	7,  // 9: hbase.pb.SnapshotRegionManifest.region_info:type_name -> hbase.pb.RegionInfo
	13, // 10: hbase.pb.SnapshotRegionManifest.family_files:type_name -> hbase.pb.SnapshotRegionManifest.FamilyFiles
	4,  // 11: hbase.pb.SnapshotDataManifest.table_schema:type_name -> hbase.pb.TableSchema
	10, // 12: hbase.pb.SnapshotDataManifest.region_manifests:type_name -> hbase.pb.SnapshotRegionManifest
	8,  // 13: hbase.pb.SnapshotRegionManifest.StoreFile.reference:type_name -> hbase.pb.Reference
	12, // 14: hbase.pb.SnapshotRegionManifest.FamilyFiles.store_files:type_name -> hbase.pb.SnapshotRegionManifest.StoreFile
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_snapshot_proto_snapshot_proto_init() }
func file_snapshot_proto_snapshot_proto_init() {
	if File_snapshot_proto_snapshot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_snapshot_proto_snapshot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_proto_snapshot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnFamilySchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_proto_snapshot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TableSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_proto_snapshot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BytesBytesPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_proto_snapshot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NameStringPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_proto_snapshot_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_proto_snapshot_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_proto_snapshot_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_proto_snapshot_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRegionManifest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_proto_snapshot_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotDataManifest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_proto_snapshot_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRegionManifest_StoreFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_snapshot_proto_snapshot_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotRegionManifest_FamilyFiles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_snapshot_proto_snapshot_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snapshot_proto_snapshot_proto_goTypes,
		DependencyIndexes: file_snapshot_proto_snapshot_proto_depIdxs,
		EnumInfos:         file_snapshot_proto_snapshot_proto_enumTypes,
		MessageInfos:      file_snapshot_proto_snapshot_proto_msgTypes,
	}.Build()
	File_snapshot_proto_snapshot_proto = out.File
	file_snapshot_proto_snapshot_proto_rawDesc = nil
	file_snapshot_proto_snapshot_proto_goTypes = nil
	file_snapshot_proto_snapshot_proto_depIdxs = nil
}
